name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]


env:
  IMAGE_TAG: 9cded2c24040edf457bafe2c8764e10abdbcb79d

jobs:

  frontend:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Backstop
        run: |
          npm install backstopjs
          npx backstop --docker reference

      - name: Lint
        run: |
          make IMAGE_TAG=${IMAGE_TAG} lint

      - name: Test
        run: |
          make IMAGE_TAG=${IMAGE_TAG} test

      - name: Smoke test
        run: |
          .github/smoke-test.sh
